# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3eccaf86150be8f3cfa5091a4a0efa49868e24239febf27934b463bbb4fa5fe9911105d3ccf8d97e1a4658fb3630ba0a910c3d4d123b89a599d65e897e66fe27

test:
  secret_key_base: 43b64833a1b904f62bd11b079a1677220f7fc8cb6de93eac0e2e0ed852415ae4c67f311d8cd2a9a59d86286f724a6d6faa278ee4afa34ff4b942ef401e438473

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
